(define (domain drone-domain)
    (:requirements :strips :typing :durative-actions :fluents)

    (:types
        location drone box person content transporter num - object
    )

    (:predicates
        (at-drone ?d - drone ?l - location)
        (at-box ?b - box ?l - location)
        (at-person ?p - person ?l - location)
        (at-transporter ?t - transporter ?l - location)
        (in-transporter ?b - box ?t - transporter)
        (box-content ?b - box ?c - content)
        (has-content ?p - person ?c - content)
        (free-drone ?d - drone)
        (free-person ?p - person)
        (free-transporter ?t - transporter)
        (free-box ?b - box)
        (holding ?d - drone ?b - box)
        (available ?b - box)
        (siguiente ?n1 ?n2 - num)
        (transporter-count ?t - transporter ?n - num)
    )

    (:functions
        (fly-cost ?from ?to - location) - number
    )

    (:durative-action pick-up
        :parameters (?d - drone ?b - box ?l - location)
        :duration (= ?duration 5)
        :condition (and
            (at start (at-drone ?d ?l))
            (at start (at-box ?b ?l))
            (at start (free-drone ?d))
            (at start (available ?b))
            (at start (free-box ?b))
            (over all (at-drone ?d ?l))
        )
        :effect (and
            (at start (not (free-drone ?d)))
            (at start (not (free-box ?b)))
            (at end (holding ?d ?b))
            (at end (not (at-box ?b ?l)))
            (at end (free-drone ?d))
            (at end (free-box ?b))
        )
    )

    (:durative-action drop
        :parameters (?d - drone ?b - box ?l - location)
        :duration (= ?duration 5)
        :condition (and
            (at start (holding ?d ?b))
            (at start (at-drone ?d ?l))
            (at start (free-drone ?d))
            (at start (free-box ?b))
            (over all (at-drone ?d ?l))
        )
        :effect (and
            (at start (not (free-drone ?d)))
            (at start (not (free-box ?b)))
            (at end (not (holding ?d ?b)))
            (at end (at-box ?b ?l))
            (at end (free-drone ?d))
            (at end (free-box ?b))
        )
    )

    (:durative-action deliver
        :parameters (?d - drone ?p - person ?b - box ?l - location ?c - content)
        :duration (= ?duration 5)
        :condition (and
            (at start (at-drone ?d ?l))
            (at start (at-person ?p ?l))
            (at start (holding ?d ?b))
            (at start (box-content ?b ?c))
            (at start (available ?b))
            (at start (free-drone ?d))
            (at start (free-person ?p))
            (at start (free-box ?b))
            (over all (at-drone ?d ?l))
            (over all (at-person ?p ?l))
        )
        :effect (and
            (at start (not (free-drone ?d)))
            (at start (not (available ?b)))
            (at start (not (free-box ?b)))
            (at start (not (free-person ?p)))
            (at end (not (holding ?d ?b)))
            (at end (has-content ?p ?c))
            (at end (free-drone ?d))
            (at end (at-box ?b ?l))
            (at end (free-box ?b))
            (at end (free-person ?p))
        )
    )

    (:durative-action move-transporter
        :parameters (?d - drone ?from - location ?to - location ?t - transporter)
        :duration (= ?duration (fly-cost ?from ?to))
        :condition (and
            (at start (at-drone ?d ?from))
            (at start (at-transporter ?t ?from))
            (at start (free-drone ?d))
            (at start (free-transporter ?t))
        )
        :effect (and
            (at start (not (at-drone ?d ?from)))
            (at start (not (at-transporter ?t ?from)))
            (at start (not (free-drone ?d)))
            (at start (not (free-transporter ?t)))
            (at end (at-drone ?d ?to))
            (at end (at-transporter ?t ?to))
            (at end (free-drone ?d))
            (at end (free-transporter ?t))
        )
    )

    (:durative-action load-onto-transporter
        :parameters (?d - drone ?b - box ?t - transporter ?l - location ?actual ?sig - num)
        :duration (= ?duration 5)
        :condition (and
            (at start (at-drone ?d ?l))
            (at start (at-transporter ?t ?l))
            (at start (holding ?d ?b))
            (at start (transporter-count ?t ?actual))
            (at start (siguiente ?actual ?sig))
            (at start (free-drone ?d))
            (at start (free-transporter ?t))
            (at start (free-box ?b))
            (over all (at-drone ?d ?l))
            (over all (at-transporter ?t ?l))
        )
        :effect (and
            (at start (not (free-drone ?d)))
            (at start (not (transporter-count ?t ?actual)))
            (at start (not (free-box ?b)))
            (at start (not (free-transporter ?t)))
            (at end (not (holding ?d ?b)))
            (at end (in-transporter ?b ?t))
            (at end (free-drone ?d))
            (at end (transporter-count ?t ?sig))
            (at end (free-box ?b))
            (at end (free-transporter ?t))
        )
    )

    (:durative-action unload-from-transporter
        :parameters (?d - drone ?b - box ?t - transporter ?l - location ?anterior ?actual - num)
        :duration (= ?duration 5)
        :condition (and
            (at start (in-transporter ?b ?t))
            (at start (free-drone ?d))
            (at start (transporter-count ?t ?actual))
            (at start (at-drone ?d ?l))
            (at start (at-transporter ?t ?l))
            (at start (siguiente ?anterior ?actual))
            (at start (free-box ?b))
            (at start (free-transporter ?t))
            (over all (at-drone ?d ?l))
            (over all (at-transporter ?t ?l))
        )
        :effect (and
            (at start (not (in-transporter ?b ?t)))
            (at start (not (free-drone ?d)))
            (at start (not (transporter-count ?t ?actual)))
            (at start (not (free-box ?b)))
            (at start (not (free-transporter ?t)))
            (at end (holding ?d ?b))
            (at end (transporter-count ?t ?anterior))
            (at end (free-drone ?d))
            (at end (free-transporter ?t))
            (at end (free-box ?b))
        )
    )
)